spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
        ddl-auto: create-drop
application:
  title: Akbank Bootcamp Homework
  version: 1.0.0